# Jobs on pull request
name: Pull request
on: pull_request

jobs:
  format:
    name: format rust files
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
      - name: format files
        run: cargo fmt --all --check

  lint:
    name: lint all rust files
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
      - name: Clippy
        run: cargo clippy --no-deps

  test:
    name: test rust files
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
      - name: run tests
        run: cargo test --workspace
